CREATE DATABASE data_analysis;
USE data_analysis;
select * from customer_shopping_behavior_s;

-- 1.what is the total revenue generated by male vs and female customer\
select gender, sum(purchase_amount) as revenue 
from customer_shopping_behavior_s 
group by gender;

-- 2.which customer used discount but still spent more than the average purchase amount

select customer_id, purchase_amount
from customer_shopping_behavior_s 
where discount_applied='Yes' and purchase_amount > (select avg(purchase_amount) 
from customer_shopping_behavior_s);

-- 3.which are the top 5 products with the highest avg review rating
select item_purchased, round(avg(review_rating),2) as avg
from customer_shopping_behavior_s
group by item_purchased 
order by avg desc
limit 5;

-- 4.compare the avg purchase amounts between standard and express shipping
select shipping_type, round(avg(purchase_amount),2)
from customer_shopping_behavior_s
where shipping_type in (lower('express'), lower('standard'))
group by shipping_type ;

-- 5.do subscribed customers spend more? compare avg spend and total
-- revenue between subscribers ans non subscribers

select subscription_status, 
count(customer_id) as total_customers,sum(purchase_amount) as total_revenue, round(avg(purchase_amount),2) as avg_spend
from customer_shopping_behavior_s
group by subscription_status;

-- 6.which 5 products have the highest percentage of purchases with discount applied
-- ( we want to see which product purchased more number of times 
-- with discount and withput in percentage

select item_purchased,
round(SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END )/ count(*) * 100,2) as discount_rate
from customer_shopping_behavior_s
group by item_purchased
order by discount_rate desc limit 5;

-- 7. segment customers into new, returning, and loyal based customers based on their
-- previous purchases and show the count of each segment


WITH customer_type as(
select customer_id, previous_purchases ,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS 'customer_segment'
from customer_shopping_behavior_s
)
select customer_segment, count(customer_segment) as no_of_customers
from customer_type
group by customer_segment;

-- what are top 3 most purchased products within each category



with item_counts as(
select category, item_purchased, count(customer_id) as no_count,row_number() over (partition by category order by count(customer_id) desc) as row_num
from customer_shopping_behavior_s
group by category, item_purchased 
order by category desc)
select * from item_counts where row_num<4 order by category;

-- are customer who are repeat buyers( more than 5 purchases) also likely to subscribe?
select subscription_status, count(customer_id)
from customer_shopping_behavior_s
where previous_purchases > 5 
group by subscription_status;

-- what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as revenue
from customer_shopping_behavior_s
group by age_group
order by revenue desc;


    

